version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y nginx
 
  build:
    commands:
      - echo "Building website..."  # Optional placeholder
 
post_build:
  commands:
    - cp -r --include="*.html *.js *.css" . /var/www/html

artifacts:
  files:
    - index.html
    - script.js
    - styles.css
