# version: 0.2
# phases:
#   build:
#     commands:
#       - echo "Building website..."

# artifacts:
#   files:
#     - index.html
#     - script.js
#     - styles.css



version: 0.2
 
phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y nginx
 
  build:
    commands:
      - echo "Building website..."  # Optional placeholder
 
post_build:
  commands:
    - cp -r . /usr/share/nginx/html  # Copy website files to document root

